/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wmjmQlBhFpO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export function Blog() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b shadow-sm">
        <div className="container mx-auto px-4 md:px-6 py-4 flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="w-6 h-6" />
            <span className="text-lg font-bold">Blog</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              Home
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              About
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              Blog
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              Contact
            </Link>
          </nav>
          <div className="relative flex-1 max-w-md">
            <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground">
              <SearchIcon className="w-4 h-4" />
            </div>
            <Input
              type="search"
              placeholder="Search..."
              className="w-full rounded-lg bg-background pl-8"
            />
          </div>
        </div>
      </header>
      <main className="flex-1 container mx-auto px-4 md:px-6 py-8 grid grid-cols-1 md:grid-cols-[3fr_1fr] gap-8">
        <div className="space-y-8">
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Future of Web Development
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Rise of Artificial Intelligence
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Impact of Remote Work
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Future of Blockchain Technology
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Rise of Sustainable Fashion
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Blog post image"
                width={400}
                height={225}
                className="rounded-t-lg object-cover w-full aspect-[16/9]"
              />
              <CardContent>
                <h2 className="text-xl font-bold tracking-tight">
                  The Future of Renewable Energy
                </h2>
                <p className="text-muted-foreground line-clamp-3">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                  euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl,
                  eget aliquam nisl nisl sit amet nisl.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="#" className="text-primary" prefetch={false}>
                  Read more
                </Link>
              </CardFooter>
            </Card>
          </div>
        </div>
        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle>Categories</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                <li>
                  <Link
                    href="#"
                    className="text-muted-foreground hover:text-foreground"
                    prefetch={false}
                  >
                    Technology
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="text-muted-foreground hover:text-foreground"
                    prefetch={false}
                  >
                    Business
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="text-muted-foreground hover:text-foreground"
                    prefetch={false}
                  >
                    Lifestyle
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="text-muted-foreground hover:text-foreground"
                    prefetch={false}
                  >
                    Travel
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="text-muted-foreground hover:text-foreground"
                    prefetch={false}
                  >
                    Health
                  </Link>
                </li>
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Tags</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  Web Development
                </Link>
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  AI
                </Link>
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  Remote Work
                </Link>
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  Blockchain
                </Link>
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  Sustainability
                </Link>
                <Link
                  href="#"
                  className="bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm"
                  prefetch={false}
                >
                  Renewable Energy
                </Link>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Recent Posts</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-4">
                <li>
                  <Link
                    href="#"
                    className="flex items-center gap-4"
                    prefetch={false}
                  >
                    <img
                      src="/placeholder.svg"
                      alt="Blog post image"
                      width={64}
                      height={64}
                      className="rounded-lg object-cover"
                    />
                    <div>
                      <h3 className="text-lg font-bold">
                        The Future of Web Development
                      </h3>
                      <p className="text-muted-foreground line-clamp-2">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      </p>
                    </div>
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="flex items-center gap-4"
                    prefetch={false}
                  >
                    <img
                      src="/placeholder.svg"
                      alt="Blog post image"
                      width={64}
                      height={64}
                      className="rounded-lg object-cover"
                    />
                    <div>
                      <h3 className="text-lg font-bold">
                        The Rise of Artificial Intelligence
                      </h3>
                      <p className="text-muted-foreground line-clamp-2">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      </p>
                    </div>
                  </Link>
                </li>
                <li>
                  <Link
                    href="#"
                    className="flex items-center gap-4"
                    prefetch={false}
                  >
                    <img
                      src="/placeholder.svg"
                      alt="Blog post image"
                      width={64}
                      height={64}
                      className="rounded-lg object-cover"
                    />
                    <div>
                      <h3 className="text-lg font-bold">
                        The Impact of Remote Work
                      </h3>
                      <p className="text-muted-foreground line-clamp-2">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      </p>
                    </div>
                  </Link>
                </li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="bg-muted py-6 border-t">
        <div className="container mx-auto px-4 md:px-6 flex items-center justify-between">
          <p className="text-muted-foreground text-sm">
            &copy; 2024 Blog. All rights reserved.
          </p>
          <nav className="flex items-center gap-4">
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground text-sm"
              prefetch={false}
            >
              Privacy Policy
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground text-sm"
              prefetch={false}
            >
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
